CREATE SEQUENCE IF NOT EXISTS public.app_content_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.course_templates_id_seq;

CREATE TABLE IF NOT EXISTS public."app_content" (
  "id" integer NOT NULL DEFAULT nextval('app_content_id_seq'::regclass),
  "key" character varying(255) NOT NULL,
  "content" text NOT NULL,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public."app_settings" (
  "key" text NOT NULL,
  "value" jsonb NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."applications" (
  "id" bigint NOT NULL,
  "student_name" text NOT NULL,
  "phone" text NOT NULL,
  "email" text NOT NULL,
  "course" text NOT NULL,
  "branch" text NOT NULL,
  "application_id" text,
  "status" text DEFAULT 'New'::text,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "address" text,
  "dob" date,
  "gender" text,
  "college_company" text,
  "photo_url" text,
  "signature_url" text,
  "id_proof_url" text,
  "marksheet_10th_url" text,
  "marksheet_12th_url" text,
  "marksheet_degree_url" text,
  "course_start_date" date,
  "course_end_date" date,
  "certificate_url" text,
  "certificate_uploaded_at" timestamp without time zone,
  "fee_total" numeric,
  "fee_gst_amount" numeric,
  "fee_main_branch_amount" numeric,
  "fee_franchise_branch_amount" numeric,
  "is_scholarship" boolean DEFAULT false,
  "scholarship_percent" numeric DEFAULT 0,
  "fee_discount_amount" numeric DEFAULT 0,
  "marks_10th" numeric,
  "marks_12th" numeric,
  "marks_ug" numeric,
  "marks_average" numeric,
  "scholarship_category" text,
  "payment_status" text DEFAULT 'Pending'::text,
  "payment_amount" numeric DEFAULT 0,
  "payment_date" timestamp with time zone,
  "payment_method" text,
  "payment_transaction_id" text,
  "payment_notes" text,
  "referral_phone_1" text,
  "referral_phone_2" text,
  "referral1_name" text,
  "referral1_email" text,
  "referral1_contact_no" text,
  "referral1_occupation" text,
  "referral2_name" text,
  "referral2_email" text,
  "referral2_contact_no" text,
  "referral2_occupation" text,
  "certificate_number" text,
  "software_covered" text,
  "payment_last_date" date,
  "payment_type" text,
  "installments_count" integer DEFAULT 0,
  "penalty_amount" numeric DEFAULT 0,
  "father_name" text,
  "mother_name" text,
  "previous_school" text,
  "previous_marks" text,
  "aadhar_number" character varying(20),
  "pan_number" character varying(20)
);

CREATE TABLE IF NOT EXISTS public."branches" (
  "id" bigint NOT NULL,
  "name" text NOT NULL,
  "code" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public."certificate_settings" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "key" text NOT NULL,
  "value" jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."course_fees" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "course_name" text NOT NULL,
  "total_fee" numeric NOT NULL DEFAULT 0,
  "gst_percent" numeric NOT NULL DEFAULT 0,
  "main_branch_percent" numeric NOT NULL DEFAULT 0,
  "franchise_branch_percent" numeric NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone DEFAULT now(),
  "category" text DEFAULT 'Other'::text
);

CREATE TABLE IF NOT EXISTS public."course_templates" (
  "id" integer NOT NULL DEFAULT nextval('course_templates_id_seq'::regclass),
  "category" text NOT NULL,
  "template_url" text NOT NULL,
  "file_name" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "x_offset" integer,
  "y_offset" integer
);

CREATE TABLE IF NOT EXISTS public."software_items" (
  "id" bigint NOT NULL,
  "name" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "logo_url" text
);

CREATE TABLE IF NOT EXISTS public."users" (
  "id" bigint NOT NULL,
  "username" text NOT NULL,
  "password_hash" text NOT NULL,
  "role" text NOT NULL,
  "branch_id" bigint,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "permissions" jsonb DEFAULT '["view"]'::jsonb,
  "reset_token" text,
  "reset_token_expiry" timestamp with time zone,
  "email" text
);

DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'software_items_pkey') THEN
            ALTER TABLE public."software_items" ADD PRIMARY KEY ("id");
        END IF;
        END $$;

DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'certificate_settings_pkey') THEN
            ALTER TABLE public."certificate_settings" ADD PRIMARY KEY ("id");
        END IF;
        END $$;

DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'course_templates_pkey') THEN
            ALTER TABLE public."course_templates" ADD PRIMARY KEY ("id");
        END IF;
        END $$;

DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'branches_pkey') THEN
            ALTER TABLE public."branches" ADD PRIMARY KEY ("id");
        END IF;
        END $$;

DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_pkey') THEN
            ALTER TABLE public."users" ADD PRIMARY KEY ("id");
        END IF;
        END $$;

DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'applications_pkey') THEN
            ALTER TABLE public."applications" ADD PRIMARY KEY ("id");
        END IF;
        END $$;

DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'course_fees_pkey') THEN
            ALTER TABLE public."course_fees" ADD PRIMARY KEY ("id");
        END IF;
        END $$;

DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'app_settings_pkey') THEN
            ALTER TABLE public."app_settings" ADD PRIMARY KEY ("key");
        END IF;
        END $$;

DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'app_content_pkey') THEN
            ALTER TABLE public."app_content" ADD PRIMARY KEY ("id");
        END IF;
        END $$;


-- Data for Name: software_items; Type: TABLE DATA
INSERT INTO public."software_items" ("id", "name", "created_at", "logo_url") VALUES ('1', 'AutoCAD', '2026-02-20T09:20:06.064Z', NULL);
INSERT INTO public."software_items" ("id", "name", "created_at", "logo_url") VALUES ('2', 'Revit', '2026-02-20T09:20:06.064Z', NULL);
INSERT INTO public."software_items" ("id", "name", "created_at", "logo_url") VALUES ('3', 'STAAD.Pro', '2026-02-20T09:20:06.064Z', NULL);
INSERT INTO public."software_items" ("id", "name", "created_at", "logo_url") VALUES ('4', 'MS Office', '2026-02-20T09:20:06.064Z', NULL);
INSERT INTO public."software_items" ("id", "name", "created_at", "logo_url") VALUES ('5', 'Tally', '2026-02-20T09:20:06.064Z', NULL);
INSERT INTO public."software_items" ("id", "name", "created_at", "logo_url") VALUES ('6', 'Python', '2026-02-20T09:20:06.064Z', NULL);
INSERT INTO public."software_items" ("id", "name", "created_at", "logo_url") VALUES ('7', 'Java', '2026-02-20T09:20:06.064Z', NULL);

-- Data for Name: certificate_settings; Type: TABLE DATA
INSERT INTO public."certificate_settings" ("id", "key", "value", "created_at", "updated_at") VALUES ('a179f7aa-7dfd-4f65-8b74-4247fdd44e6d', 'coordinates', '{"color":"#000000","branch":{"x":450,"y":1459,"fontSize":28},"duration":{"x":450,"y":1185,"fontSize":28},"issued_on":{"x":450,"y":1279,"fontSize":28},"admission_no":{"x":315,"y":900,"fontSize":28},"course_title":{"x":450,"y":1095,"fontSize":28},"student_name":{"x":450,"y":1000,"fontSize":28},"partner_logos":{"x":450,"y":1650,"width":150,"height":80},"certificate_no":{"x":950,"y":900,"fontSize":28},"software_covered":{"x":450,"y":1375,"fontSize":28}}', '2026-02-20T10:53:37.296Z', '2026-02-20T10:53:37.296Z');
INSERT INTO public."certificate_settings" ("id", "key", "value", "created_at", "updated_at") VALUES ('d400ab0c-0738-43a9-b1d2-13d3336a7a72', 'templates', '{"mechanic":"https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/software_logos/custom_template_mechanic.jpg","standard":"https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/software_logos/custom_template_standard.png"}', '2026-02-20T10:53:37.296Z', '2026-02-20T10:53:37.296Z');
INSERT INTO public."certificate_settings" ("id", "key", "value", "created_at", "updated_at") VALUES ('05a86b26-11e1-4509-bf47-4ccf3b1b2522', 'category_logos', '{"Arts":[],"Kids":[],"Civil":[],"CSE / IT":[],"Mechanical":[]}', '2026-02-20T11:09:21.972Z', '2026-02-20T11:09:21.972Z');

-- Data for Name: course_templates; Type: TABLE DATA
INSERT INTO public."course_templates" ("id", "category", "template_url", "file_name", "created_at", "x_offset", "y_offset") VALUES (2, 'Mechanical', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/cert-templates/Mechanical_1771599401954.png', 'course template (1).png', '2026-02-20T14:56:42.486Z', NULL, NULL);
INSERT INTO public."course_templates" ("id", "category", "template_url", "file_name", "created_at", "x_offset", "y_offset") VALUES (3, 'Civil', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/cert-templates/Civil_1771599422278.png', 'course template (2).png', '2026-02-20T14:57:02.600Z', NULL, NULL);
INSERT INTO public."course_templates" ("id", "category", "template_url", "file_name", "created_at", "x_offset", "y_offset") VALUES (4, 'Arts', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/cert-templates/Arts_1771599463688.png', 'course template (2).png', '2026-02-20T14:57:43.992Z', NULL, NULL);
INSERT INTO public."course_templates" ("id", "category", "template_url", "file_name", "created_at", "x_offset", "y_offset") VALUES (5, 'Kids', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/cert-templates/Kids_1771599476539.png', 'course template (2).png', '2026-02-20T14:57:57.106Z', NULL, NULL);
INSERT INTO public."course_templates" ("id", "category", "template_url", "file_name", "created_at", "x_offset", "y_offset") VALUES (7, '_partner_logos', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/cert-logos/partner_1771600062693.png', 'course template (3).png', '2026-02-20T15:07:44.134Z', NULL, NULL);
INSERT INTO public."course_templates" ("id", "category", "template_url", "file_name", "created_at", "x_offset", "y_offset") VALUES (8, '_partner_logos', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/cert-logos/partner_1771600078355.png', 'Cherished moments in the afternoon light.png', '2026-02-20T15:08:00.900Z', NULL, NULL);
INSERT INTO public."course_templates" ("id", "category", "template_url", "file_name", "created_at", "x_offset", "y_offset") VALUES (9, '_partner_CSE / IT', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/cert-logos/partner_CSE_/_IT_1771600561689.png', 'course template (3).png', '2026-02-20T15:16:09.942Z', NULL, NULL);
INSERT INTO public."course_templates" ("id", "category", "template_url", "file_name", "created_at", "x_offset", "y_offset") VALUES (6, 'CSE / IT', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/cert-templates/CSE___IT_1771599493776.png', 'course template (3).png', '2026-02-20T14:58:14.093Z', 84, 1856);
INSERT INTO public."course_templates" ("id", "category", "template_url", "file_name", "created_at", "x_offset", "y_offset") VALUES (12, '_partner_CSE / IT', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/cert-logos/partner_CSE_/_IT_1771652471159.png', 'download (1).png', '2026-02-21T05:41:10.364Z', NULL, NULL);

-- Data for Name: branches; Type: TABLE DATA
INSERT INTO public."branches" ("id", "name", "code", "created_at") VALUES ('2', 'Gandhipuram Branch', 'Gandhipuram', '2026-02-12T12:20:06.016Z');
INSERT INTO public."branches" ("id", "name", "code", "created_at") VALUES ('1', 'Peelamedu Branch', 'MAIN', '2026-02-12T12:20:06.016Z');

-- Data for Name: users; Type: TABLE DATA
INSERT INTO public."users" ("id", "username", "password_hash", "role", "branch_id", "created_at", "permissions", "reset_token", "reset_token_expiry", "email") VALUES ('16', 'sneha', 's1403', 'franchise_owner', '2', '2026-02-13T07:47:18.617Z', '["view"]', NULL, NULL, NULL);
INSERT INTO public."users" ("id", "username", "password_hash", "role", "branch_id", "created_at", "permissions", "reset_token", "reset_token_expiry", "email") VALUES ('17', 'kema', 'k123', 'user', '2', '2026-02-13T07:49:10.498Z', '["view"]', NULL, NULL, NULL);
INSERT INTO public."users" ("id", "username", "password_hash", "role", "branch_id", "created_at", "permissions", "reset_token", "reset_token_expiry", "email") VALUES ('19', 'admin1', '123456', 'franchise_owner', '1', '2026-02-20T08:59:14.589Z', '["view"]', NULL, NULL, '24pa03@psgtech.ac.in');
INSERT INTO public."users" ("id", "username", "password_hash", "role", "branch_id", "created_at", "permissions", "reset_token", "reset_token_expiry", "email") VALUES ('20', 'jetski_admin', 'password123', 'super_admin', NULL, '2026-02-24T05:31:45.806Z', '["view"]', NULL, NULL, NULL);
INSERT INTO public."users" ("id", "username", "password_hash", "role", "branch_id", "created_at", "permissions", "reset_token", "reset_token_expiry", "email") VALUES ('1', 'admin', '654321', 'super_admin', NULL, '2026-02-12T12:20:06.016Z', '["view"]', 'ab1bb8351991fa45f49151de54a7b3b62bc2b80ca07b66c1afd266df059b643a', '2026-02-24T11:15:22.622Z', '24pa21@psgtech.ac.in');

-- Data for Name: applications; Type: TABLE DATA
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('10', 'Test Student Referral', '1234567890', 'testreferral@example.com', 'Test Course', 'Test Branch', 'APP/TES/2026/1420', 'New', '2026-02-13T08:07:34.163Z', 'Test Address', '1999-12-31T18:30:00.000Z', 'Male', 'Test College', NULL, NULL, NULL, NULL, NULL, NULL, '2023-12-31T18:30:00.000Z', '2024-05-31T18:30:00.000Z', NULL, NULL, NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('7', 'ds', '6549873210', '24pa21@psgtech.ac.in', 'Software Testing', 'Main Branch', 'APP/MAI/2026/3276', 'Completed', '2026-02-12T18:17:49.409Z', 'bvn', '2026-02-05T18:30:00.000Z', 'Female', 'bv', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.7055157312652712.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.47769490711647755.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.08582039959380316.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.5216027247253684.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.6223033290589096.jpeg', NULL, '2026-02-13T18:30:00.000Z', '2026-02-15T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP-MAI-2026-3276_1771650608040.pdf', '2026-02-20T23:40:09.541Z', '5000', '500', '2250', '2250', false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TN/CBE/043/APP/MAI/2026/3276', 'Test Software 1, Test Software 2', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('4', 'mb', '6549873210', '24pa21@psgtech.ac.in', 'Software Testing', 'Main Branch', 'APP/MAI/2026/2550', 'Completed', '2026-02-12T16:37:13.500Z', 'bvn', '2026-02-05T18:30:00.000Z', 'Male', 'bv', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.8833515723527391.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.7793487360848784.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.7069670786635985.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.16084158246033753.pdf', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.14658061526422772.pdf', NULL, '2026-02-09T18:30:00.000Z', '2026-02-13T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP-MAI-2026-2550_1771924584755.pdf', '2026-02-24T03:46:25.356Z', NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TN/CBE/043/APP/MAI/2026/2550', 'Python', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('3', 'veera', '1234567890', '24pa21@psgtech.ac.in', 'Creo Parametric', 'Main Branch', 'APP/MAI/2026/4546', 'Enrolled', '2026-02-12T16:27:41.279Z', 'hbhj', '2026-01-31T18:30:00.000Z', 'Female', 'jkhkhk', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.6547424734358466.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.3261933261935468.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.569095817488475.pdf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('14', 'Test Student', '9876543210', 'test.student@example.com', 'Full Stack Development', 'Main Branch', 'APP/MAI/2026/7748', 'Completed', '2026-02-19T05:08:19.885Z', '123 Test St', '1999-12-31T18:30:00.000Z', 'Male', 'Test College', 'http://example.com/photo.jpg', 'http://example.com/sig.jpg', 'http://example.com/id.jpg', 'http://example.com/10.jpg', 'http://example.com/12.jpg', 'http://example.com/deg.jpg', '2022-12-31T18:30:00.000Z', '2023-05-31T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP/MAI/2026/7748_1771605247474.pdf', '2026-02-20T11:04:10.619Z', '50000', '9000', '41000', '0', false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'STAAD.Pro', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('1', 'hfdgr', '5867867', '24pa21@psgtech.ac.in', 'Data Analytics', 'Main Branch', 'APP/MAI/2026/8504', 'Enrolled', '2026-02-12T15:15:25.140Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('6', 'Test No Alert Student', '8888888888', 'test@noalert.com', 'B.Tech', 'Computer Science', 'APP/COM/2026/8760', 'Completed', '2026-02-12T17:34:01.766Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-11T18:30:00.000Z', '2026-02-21T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP-COM-2026-8760_1771915376762.pdf', '2026-02-24T01:12:57.511Z', NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TN/CBE/043/APP/COM/2026/8760', 'Python', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('13', 'kems', '6549873210', '24pa21@psgtech.ac.in', 'Full Stack Development', 'Main Branch', 'APP/MAI/2026/1753', 'Completed', '2026-02-18T04:59:03.831Z', 'nytu7t7ti7tiiy', '2026-02-02T18:30:00.000Z', 'Female', 'gtyuikjlk;p', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.7149150264386934.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.25776403058102504.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.8783217175491626.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.9105428104611688.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.6320214386024164.pdf', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_degree_0.5229004283142294.pdf', '2026-02-15T18:30:00.000Z', '2026-02-27T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP-MAI-2026-1753_1771648482341.pdf', '2026-02-20T23:04:43.789Z', '69999', '10709.847', '29273.5818', '19515.7212', true, '15.00', '10499.85', '50.00', '60.00', '82.00', '64.00', 'IT', 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, 'gut77', '24pa21@psgtech.ac.in', '7757878677', 'hgyrrwewre', 'hfdgr', '24pa21@psgtech.ac.in', '7757878677', 'ghtrh', 'TN/CBE/043/APP/MAI/2026/1753', 'STAAD.Pro', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('8', 'ds', '6549873210', '24pa21@psgtech.ac.in', 'Software Testing', 'City Branch', 'APP/CIT/2026/5218', 'Completed', '2026-02-13T05:18:50.299Z', 'bvn', '2026-02-05T18:30:00.000Z', 'Female', 'bvgh', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.9145891027911478.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.9719016001958988.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.814609439167425.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.6513492832911161.pdf', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.7331013276853129.png', NULL, '2026-02-28T18:30:00.000Z', '2026-02-24T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP-CIT-2026-5218_1771650266091.pdf', '2026-02-20T23:34:27.290Z', '5000', '425', '1912.5', '1912.5', true, '15.00', '750.00', '60.00', '60.00', '60.00', '60.00', 'IT', 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TN/CBE/043/APP/CIT/2026/5218', 'Java', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('11', 'Test Student Missing Referral', '1234567891', 'testmissing@example.com', 'Test Course', 'Test Branch', 'APP/TES/2026/6118', 'Completed', '2026-02-13T08:07:43.514Z', 'Test Address', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP-TES-2026-6118_1771655809305.pdf', '2026-02-21T01:06:50.077Z', NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TN/CBE/043/APP/TES/2026/6118', 'Python, STAAD.Pro', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('5', 'Test Alert Student', '9999999999', 'test@alert.com', 'B.Tech', 'Computer Science', 'APP/COM/2026/4787', 'Completed', '2026-02-12T17:34:01.085Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-02-11T18:30:00.000Z', '2026-02-16T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP-COM-2026-4787_1771924544881.pdf', '2026-02-24T03:45:45.453Z', NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TN/CBE/043/APP/COM/2026/4787', 'AutoCAD, MS Office, Revit', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('18', 'hema', '6549873210', '24pa21@psgtech.ac.in', 'Robotics for Kids', 'Main Branch', 'APP/LASAK/MAIN_BRANCH/11', 'Completed', '2026-02-19T05:36:24.556Z', 'nytu7t7ti7tiiy', '2026-02-18T18:30:00.000Z', 'Male', 'gtyuikjlk;p', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.17857787636182365.jpg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.8566359922536221.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.3239047048600331.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.27893842000325375.pdf', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.2329095942498377.pdf', NULL, '2026-02-15T18:30:00.000Z', '2026-02-27T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP-LASAK-MAIN_BRANCH-11_1771653676465.pdf', '2026-02-21T00:31:17.382Z', '5000', '855', '2337', '1558', true, '5.00', '250.00', '50.00', '60.00', '82.00', '64.00', 'General', 'Paid', '5000.00', '2026-02-24T00:00:00.000Z', 'Cash', '', NULL, NULL, NULL, 'gut77', '24pa21@psgtech.ac.in', '7757878677', 'hgyrrwewre', 'hfdgr', '24pa21@psgtech.ac.in', '7757878677', 'ghtrh', 'TN/CBE/043/APP/LASAK/MAIN_BRANCH/11', 'AutoCAD, MS Office', '2026-02-14T18:30:00.000Z', NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('16', 'Test Student Seq 1', '1111111111', 'test.seq1@example.com', 'Testing', 'Test Branch Sequence', 'APP/LASAK/TEST_BRANCH_SEQUENCE/1', 'Completed', '2026-02-19T05:31:26.397Z', '123 Test St', '1999-12-31T18:30:00.000Z', 'Male', 'Test College', 'http://example.com/photo.jpg', 'http://example.com/sig.jpg', 'http://example.com/id.jpg', 'http://example.com/10.jpg', 'http://example.com/12.jpg', 'http://example.com/deg.jpg', '2022-12-31T18:30:00.000Z', '2023-05-31T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP/LASAK/TEST_BRANCH_SEQUENCE/1_1771580727345.pdf', '2026-02-20T04:15:28.011Z', '50000', '9000', '41000', '0', false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AutoCAD, MS Office, Revit', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('17', 'Test Student Seq 2', '1111111111', 'test.seq1@example.com', 'Testing', 'Test Branch Sequence', 'APP/LASAK/TEST_BRANCH_SEQUENCE/2', 'Completed', '2026-02-19T05:31:26.944Z', '123 Test St', '1999-12-31T18:30:00.000Z', 'Male', 'Test College', 'http://example.com/photo.jpg', 'http://example.com/sig.jpg', 'http://example.com/id.jpg', 'http://example.com/10.jpg', 'http://example.com/12.jpg', 'http://example.com/deg.jpg', '2022-12-31T18:30:00.000Z', '2023-05-31T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP/LASAK/TEST_BRANCH_SEQUENCE/2_1771581142357.pdf', '2026-02-20T04:22:22.948Z', '50000', '9000', '41000', '0', false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AutoCAD, Java, MS Office, Python, STAAD.Pro, Revit, Tally', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('15', 'veera', '6549873210', '24pa21@psgtech.ac.in', 'Digital Marketing (Adv)', 'Main Branch', 'APP/MAI/2026/1064', 'Completed', '2026-02-19T05:11:19.833Z', 'nytu7t7ti7tiiy', '2026-02-08T18:30:00.000Z', 'Female', 'gtyuikjlk;p', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.9126038689177199.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.16100463204784987.jpg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.9584626798905289.pdf', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.3933724572240227.pdf', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.9212691199612553.pdf', NULL, '2026-02-15T18:30:00.000Z', '2026-02-27T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP/MAI/2026/1064_1771581954347.pdf', '2026-02-20T04:35:55.077Z', '29999', '2969.9010000000003', '8117.7294', '5411.819600000001', true, '45.00', '13499.55', '90.00', '90.00', '90.00', '90.00', 'IT', 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, 'gut77', '24pa21@psgtech.ac.in', '7757878677', 'hgyrrwewre', 'hfdgr', '24pa21@psgtech.ac.in', '7757878677', 'ghtrh', NULL, 'STAAD.Pro', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('2', 'kema', '1234567890', '24pa21@psgtech.ac.in', 'Computational Fluid Dynamics (CFD)', 'Main Branch', 'APP/MAI/2026/2980', 'Completed', '2026-02-12T16:17:15.012Z', 'bhjvh', '2026-02-01T18:30:00.000Z', 'Female', 'jkhkhk', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.07673871907087604.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.9910534140613122.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.3654735626199025.pdf', NULL, NULL, NULL, NULL, NULL, 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP/MAI/2026/2980_1771604554779.pdf', '2026-02-20T10:52:36.459Z', NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MS Office, Revit, Tally', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('9', 'dv', '6549873210', '24pa21@psgtech.ac.in', 'Software Testing', 'Main Branch', 'APP/MAI/2026/3766', 'Completed', '2026-02-13T05:29:04.520Z', 'bvn', '2026-02-05T18:30:00.000Z', 'Female', 'bv', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.27840821881086264.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.3894598798837079.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.6703267768958086.jpeg', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.016954986059991684.pdf', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.07701042054048568.pdf', NULL, '2026-02-12T18:30:00.000Z', '2026-02-22T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP/MAI/2026/3766_1771605938212.pdf', '2026-02-20T11:15:45.060Z', '5000', '275', '1237.5', '1237.5', true, '45.00', '2250.00', '90.00', '100.00', '100.00', '96.67', 'IT', 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Java', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('12', 'hfdgr', '6549873210', '24pa21@psgtech.ac.in', 'Software Testing', 'Main Branch', 'APP/MAI/2026/8596', 'Completed', '2026-02-16T09:31:04.065Z', 'nytu7t7ti7tiiy', '6666-06-06T18:30:00.000Z', 'Female', 'gtyuikjlk;p', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.08981220954213598.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.9397586073038817.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.7887905755055016.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.11187121332203265.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.4346693887174279.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_degree_0.6133042923729821.png', '6788-04-04T18:30:00.000Z', '7789-06-05T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_APP/MAI/2026/8596_1771606779303.pdf', '2026-02-20T11:29:43.347Z', '5000', '275', '1237.5', '1237.5', true, '45.00', '2250.00', '89.00', '90.00', '90.00', '89.67', 'IT', 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, 'gut77', '24pa21@psgtech.ac.in', '7757878677', 'hgyrrwewre', '', '', '', '', NULL, 'Python', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('22', 'ds', '6549873210', '24pa21@psgtech.ac.in', '3D Printing & Prototyping', 'Gandhipuram Branch', 'LTIEC0022', 'New', '2026-02-22T06:16:59.667Z', 'utyu7t6u', '2026-02-04T18:30:00.000Z', 'Female', 'bv', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.9988449760423698.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.9252579871737792.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.9661556603598863.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.6554608799414413.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.6522951095708011.png', NULL, '2026-02-19T18:30:00.000Z', '2026-02-14T18:30:00.000Z', NULL, NULL, '1', '0.18', '0.49200000000000005', '0.32800000000000007', false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Paid', '1.00', '2026-02-22T06:17:01.050Z', 'Razorpay', 'pay_SJ5b7kUPomMBiK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hfdgr', '24pa21@psgtech.ac.in', '7757878677', 'bcvbgfh', 'TN/CBE/043/LTIEC0022', NULL, '2026-02-28T18:30:00.000Z', 'Full', 0, '0', NULL, NULL, 'hjfhyujv', '', NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('19', 'hema', '6549873210', '24pa21@psgtech.ac.in', 'Digital Marketing (Adv)', 'Gandhipuram Branch', 'LTIEC0019', 'Completed', '2026-02-20T10:25:56.614Z', 'nytu7t7ti7tiiy', '2026-02-18T18:30:00.000Z', 'Female', 'gtyuikjlk;p', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.9217384021890881.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.4993106336575317.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.7113294444393039.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.04078731868131602.pdf', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.3279914854210828.pdf', NULL, '2026-02-15T18:30:00.000Z', '2026-02-27T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_LTIEC0019_1771652102936.pdf', '2026-02-21T00:05:04.351Z', '29999', '4319.856000000001', '11807.6064', '7871.7376', true, '20.00', '5999.80', '56.00', '67.00', '76.00', '66.33', 'IT', 'Partial', '100.00', '2026-02-22T00:00:00.000Z', 'Cash', '', NULL, NULL, NULL, 'gut77', '24pa21@psgtech.ac.in', '7757878677', 'hgyrrwewre', 'hfdgr', '24pa21@psgtech.ac.in', '7757878677', 'ghtrh', 'TN/CBE/043/LTIEC0019', 'STAAD.Pro', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('20', 'TEST STUDENT - 1771648393781', '1234567890', 'test@example.com', 'B.E (Computer Science and Engineering)', 'Admin Branch', 'LTIEC0020', 'Completed', '2026-02-21T04:33:13.071Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2023-12-31T18:30:00.000Z', '2024-12-30T18:30:00.000Z', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/certificates/certificate_LTIEC0020_1771651990108.pdf', '2026-02-21T00:03:12.527Z', NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TN/CBE/043/LTIEC0020', 'Python', NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('21', 'ds', '6549873210', '24pa21@psgtech.ac.in', '3D Printing & Prototyping', 'Gandhipuram Branch', 'LTIEC0021', 'New', '2026-02-21T10:21:51.194Z', 'utyu7t6u', '2026-02-04T18:30:00.000Z', 'Male', 'bv', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/photos_0.3860858960129917.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/signatures_0.13178471863160335.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/id_proofs_0.7750216689417179.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_10th_0.16948752627688668.png', 'https://txzmjjpreauzgfvzgswk.supabase.co/storage/v1/object/public/documents/marksheet_12th_0.07850601563678483.png', NULL, '2026-02-19T18:30:00.000Z', '2026-02-14T18:30:00.000Z', NULL, NULL, '1', '0.18', '0.49200000000000005', '0.32800000000000007', false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Paid', '1.00', '2026-02-21T10:21:51.958Z', 'Razorpay', 'pay_SIlEflNLV67lXl', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hfdgr', '24pa21@psgtech.ac.in', '7757878677', 'bcvbgfh', 'TN/CBE/043/LTIEC0021', NULL, '2026-02-27T18:30:00.000Z', NULL, 0, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('23', 'sneha', '6549873210', '24pa21@psgtech.ac.in', 'General Enrollment', 'Enrolled Lasak', 'LTIEC0023', 'New', '2026-02-25T10:51:53.582Z', 'rh43brh4b', '2026-01-31T18:30:00.000Z', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TN/CBE/043/LTIEC0023', NULL, NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, '123456789012', 'ABCDE1234F');
INSERT INTO public."applications" ("id", "student_name", "phone", "email", "course", "branch", "application_id", "status", "created_at", "address", "dob", "gender", "college_company", "photo_url", "signature_url", "id_proof_url", "marksheet_10th_url", "marksheet_12th_url", "marksheet_degree_url", "course_start_date", "course_end_date", "certificate_url", "certificate_uploaded_at", "fee_total", "fee_gst_amount", "fee_main_branch_amount", "fee_franchise_branch_amount", "is_scholarship", "scholarship_percent", "fee_discount_amount", "marks_10th", "marks_12th", "marks_ug", "marks_average", "scholarship_category", "payment_status", "payment_amount", "payment_date", "payment_method", "payment_transaction_id", "payment_notes", "referral_phone_1", "referral_phone_2", "referral1_name", "referral1_email", "referral1_contact_no", "referral1_occupation", "referral2_name", "referral2_email", "referral2_contact_no", "referral2_occupation", "certificate_number", "software_covered", "payment_last_date", "payment_type", "installments_count", "penalty_amount", "father_name", "mother_name", "previous_school", "previous_marks", "aadhar_number", "pan_number") VALUES ('24', 'dsg', '1234567890', 'info@lasak.in', 'General Enrollment', 'Enrolled Lasak', 'LTIEC0024', 'New', '2026-02-25T11:06:39.940Z', 'fgdfgdbhgtdhb', '2026-02-05T18:30:00.000Z', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, '0.00', '0.00', NULL, NULL, NULL, NULL, NULL, 'Pending', '0.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'TN/CBE/043/LTIEC0024', NULL, NULL, NULL, 0, '0', NULL, NULL, NULL, NULL, '123456789099', 'ABCDE1234F');

-- Data for Name: course_fees; Type: TABLE DATA
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('90fb8bf4-fd06-4084-a016-ba312efd709b', 'Scratch Coding', '4000', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Kids');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('3ef7e7c7-8c12-4833-afaa-96205b36ab55', 'Robotics for Kids', '5000', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Kids');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('6c3fd4ed-5ed5-40ed-a2d7-8b22f3367e54', 'Java Programming', '25999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'CSE / IT');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('9d0635b5-0154-4dc0-bf73-ccd9ed6f9453', 'Full Stack Development', '69999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'CSE / IT');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('0e3c90ff-f683-4c36-86e8-e157e0590630', 'Software Testing', '69999', '18', '60', '40', '2026-02-12T18:06:12.947Z', 'CSE / IT');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('2ea9c549-f7e0-4964-ae61-3956c946e714', 'UI/UX Design', '20999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'CSE / IT');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('7c810599-8e08-4fce-869c-cff8b0d66a61', 'Web Development', '36999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'CSE / IT');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('0439402c-117d-47d3-9a92-7570df4a0c2d', 'Data Analytics', '69999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'CSE / IT');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('745ddfc4-245b-4de9-bc20-c82b6eef7796', 'Python Programming', '18999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'CSE / IT');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('c876e4a8-22e8-40ce-a6c7-50f8bf7d83e7', 'Computational Fluid Dynamics (CFD)', '13999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('a6a66693-9713-45b7-a2d7-66b8f10fe3c3', 'Wiring Harness Design', '19999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('71ce2a3c-dc0d-4fd6-9c97-894efbd77633', 'Creo Parametric', '24999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('0f5924b3-0698-452a-a07d-7d44eca31836', 'SolidWorks Masterclass', '24999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('184cae67-a6fb-4fed-9c0a-af064347a4e7', 'HyperMesh', '21000', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('9a7740f6-091e-4d7e-8f67-c9e0614c9b74', 'ANSYS Simulation', '19999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('4b84dfd4-6162-4282-bc20-c0d0a808d17b', 'CATIA V5', '19999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('551c5733-bd35-48ae-8ade-33bbd89c35ea', 'ANSA Pre-processing', '17999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('36a02d21-4cf9-4fe2-9edf-8135387bfd4f', 'NX CAD (Unigraphics)', '19999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('dc435880-b6b7-41bc-b4a4-a90c3a3a0df8', 'Autodesk Inventor', '19999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('20b5548e-3d90-4b70-98c2-7391def7019b', 'AutoCAD Mechanical', '6999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('15944dda-3f16-46a1-b5fc-a5f4e4231fae', 'SketchUp', '17999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Civil');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('31716e04-86a6-4708-8d9a-d3e21ff41d52', 'Civil CAD', '7499', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Civil');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('05b30905-d8b7-4acc-bc40-22a5fb4c29c3', 'BIM Professional', '34999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Civil');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('ba95edc4-7607-4b5f-91f8-3cd5552dc1b6', 'STAAD.Pro', '17999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Civil');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('9d938a8d-6d5b-4cac-ac06-21bafd8c4d44', 'Revit Architecture', '19999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Civil');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('ff6b82ac-5d03-4906-ae91-f1e36970d223', 'Digital Marketing (Media)', '29999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Arts');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('776a489a-5383-46fb-8afb-42ed629de6d1', 'Tally with GST', '7999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Arts');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('27777873-f035-4b1e-b03a-8787f5c53d5d', 'Digital Marketing (Adv)', '29999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Arts');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('eb7cb3dd-86a0-46b2-8b0d-98b1d26e198a', 'MS Office', '8999', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Arts');
INSERT INTO public."course_fees" ("id", "course_name", "total_fee", "gst_percent", "main_branch_percent", "franchise_branch_percent", "created_at", "category") VALUES ('e2ed3c58-09d2-4f73-86f4-c852d6a94e99', '3D Printing & Prototyping', '1', '18', '60', '40', '2026-02-17T10:44:13.128Z', 'Mechanical');

-- Data for Name: app_settings; Type: TABLE DATA
INSERT INTO public."app_settings" ("key", "value", "updated_at") VALUES ('penalty_config', '{"grace_days":11,"daily_penalty_amount":50}', '2026-02-22T05:30:56.848Z');

-- Data for Name: app_content; Type: TABLE DATA
INSERT INTO public."app_content" ("id", "key", "content", "updated_at") VALUES (1, 'terms_conditions', '<div className="space-y-6 text-sm leading-relaxed">
    <section>
        <h3 className="font-bold text-base mb-2">1. Fee Structure & Payment:</h3>
        <ul className="list-disc pl-5 space-y-1">
            <li>The student agrees to pay the total course fee as specified.</li>
            <li>All installment payments must be cleared by the specified date of every month.</li>
            <li>Late payments may result in a temporary suspension of lab access.</li>
        </ul>
    </section>

    <section>
        <h3 className="font-bold text-base mb-2">2. No-Refund Policy:</h3>
        <p className="mb-2"><strong>Please read and initial the following:</strong></p>
        <p>I, the undersigned, understand that the registration and tuition fees paid to Lasak Edu are strictly non-refundable and non-transferable under any circumstances.</p>
        <p className="mt-2 text-gray-600 italic">This includes, but is not limited to:</p>
        <ul className="list-disc pl-5 space-y-1">
            <li>Withdrawal from the course before or after the start date.</li>
            <li>Inability to attend classes due to medical issues.</li>
            <li>Dismissal from the institute due to misconduct.</li>
        </ul>
    </section>

    <section>
        <h3 className="font-bold text-base mb-2">3. Attendance & Certification:</h3>
        <ul className="list-disc pl-5 space-y-1">
            <li>A minimum of 80% attendance is required to be eligible for the course completion certificate.</li>
            <li>Students are responsible for catching up on any missed material. The institute is not obligated to hold extra sessions for individual absences.</li>
        </ul>
    </section>

    <section>
        <h3 className="font-bold text-base mb-2">4. Lab & Software Usage:</h3>
        <ul className="list-disc pl-5 space-y-1">
            <li>Students must use the CADD software and hardware with care. Any intentional damage to equipment will be the financial responsibility of the student.</li>
            <li>Unauthorized copying of software or course materials is strictly prohibited.</li>
        </ul>
    </section>

    <section>
        <h3 className="font-bold text-base mb-2">5. Consent & Declaration:</h3>
        <p>I hereby declare that I have read the above terms and conditions, specifically the No-Refund Policy, and I agree to abide by them throughout my tenure at Lasak Edu.</p>
    </section>
</div>', '2026-02-17T11:41:50.723Z');
  